### PR TITLE
Wrapper code and tests for all JS clients

### PR DESCRIPTION
**Pull request by dangunter**
Wrapper APIs and tests for JS clients, along with associated docs on how to run and install.

To-do:
- [x] README
- [x] Makefile to simplify local testing
- [x] .travis.yml to run tests on TravisCI
- [x] Taxon API code and tests
- [x] Assembly API code and tests
- [x] Genome API code and tests
- [x] For binary protocol, finish all tasks in this JIRA issue: https://atlassian.kbase.us/browse/KBASE-3318 and progress tracked in github by this PR  https://github.com/kbase/thrift-js-binary-protocol/pull/1

### CODE REVIEW

**Comment by dangunter** [comment]
Although the TravisCI build is failing, these tests are working locally. So I will need to fix Travis before this PR can be accepted (by me, or anyone else)

**Comment by dangunter** [comment]
Got travis working again -- it was just a matter of adding the generated code to the repo, since Travis doesn't try to run thrift (deployment problems with that) to generate them from scratch.

**Comment by eapearson** [comment]
I can't help with merging this, but I do have a few comments:

The usage of underscore within function names -- it is normative in javascript in general, and kbase specifically to use camelCase. I think we should be consistent.

Usage of _ prefixed variables or functions within modules is not necessary since everything is private unless exported. It is a holdover from globally loaded JS files or other environments in which references can escape. Some environments (linters, ides) will complain about this. (In general I would pay close attention to jslint advice. Eventually code will go through jslint before release.)

It is much easier to trace api calls in the wrapper, and to provide internal documentation, if the wrapping functions are actually implemented as real functions. E.g. debugging in the browser, placing breakpoints, etc. I do like how concise the modules are using this technique, but think the difficulties that string based method dispatch brings to an api is not worth it.

Exceptions should now always be thrown as Error or objects derived from Error, a requirement for bluebird (it complains bitterly about this, which makes debugging difficult; but bluebird also provides a very handy way of filtering exceptions which works best with error objects) and also since the api relies on exceptions, e.g. missing attributes, but also certain protocol/transport layer errors which can be handled more gracefully if there is some finer granularity (but that should already be in place.) I know that is how I left them, and I thought it was a nice way to casually introduce more detailed and api-user friendly error messages, but I found the error of my ways. I have also put an exception object per api in my fork, but it may be that a single TaxonClientException would suffice for any client-invocation errors (arguments, etc.)

Semicolons should be used!

There is also a need to expose Thrift exceptions to the api user. I have played around with re-exporting them in each api. It makes api usage easier, because the user just has to import the one api. They could also be required to import thrift, which would implicitly bring along the protocols and transports (but in a messy way). However, that would also expose the entire thrift interface, which is not something users should be expected to do or be aware of. Simply knowing the exceptions that might be thrown, and being able to pull them off of the client module, should be enough to be able to use the api effectively. The implication of exposing more than one thing in a module is that there needs to be a function for creating an api client, rather than just using the module object.

There should not be any token validation of the token in client -- it should be considered entirely opaque.

Sorry that I went on --

**Comment by dangunter** [comment]
@mlhenderson This is ready to merge. I do want to write a few more high-level tests, and work on documentation, but that can be done in another PR.

**Comment by mlhenderson** [comment]
Thanks Dan.  We should discuss later how we could potentially make updates to the thrift specs easier to deal with here.  

Let's get this merged so we can use this for js widget code.

**Pull request merged**
